Allow the error in the classification. It can be solved in a closed form, but it takes time and almost impossible to solve when the data become too large. To get around with the problem of calculating an inverse of a large matrix, we iteratively update the weight to find the solution.

### How to update $w$
$w'_c = w_c - \rho\epsilon_{cp} x_p$


In [48]:
import numpy as np

y = np.array([1,1,0,1,0,0])
x = np.array([1.0, 0.5, -0.2, -0.4, -1.3, -2.0])
X = np.array([np.ones(len(x)), x])
rho = 0.2

In [49]:
w = np.array([0.2, 0.3])
gx = w.dot(X)
error = w.dot(X) - y
gx

array([ 0.5 ,  0.35,  0.14,  0.08, -0.19, -0.4 ])

Update $w$ by $w - \rho\epsilon_{cp}x_p$

In [50]:
error

array([-0.5 , -0.65,  0.14, -0.92, -0.19, -0.4 ])

In [52]:
0.5*np.sum(error**2)

0.8673

In [36]:
w_new = w - rho*X.dot(error)
w_new

array([0.704 , 0.1876])

Now we can iterate this calculation.

In [55]:
def update_weight(w, X, y, rho = 0.2):
    gx = w.dot(X)
    error = gx - y
    w_new = w - rho * X.dot(error)
    sqrd_error = 0.5*np.sum(error**2)
    return w_new, sqrd_error

In [56]:
update_weight(w, X, y, rho=0.2)

(array([0.704 , 0.1876]), 0.8673)

In [64]:
w = np.array([0.2, 0.3])
rho = 0.2
prev_error = 1000
for i in range(50):
    w, error = update_weight(w, X, y, rho)
    delta_error = abs(prev_error - error)
    prev_error = error
    print("{}th iteration weight={}  error={:.3f}".format(i+1, w, error))
    if delta_error > 0.000001:
        continue
    else:
        break

1th iteration weight=[0.704  0.1876]  error=0.867
2th iteration weight=[0.549248  0.4776272]  error=0.477
3th iteration weight=[0.71941146 0.2792146 ]  error=0.417
4th iteration weight=[0.59014072 0.44581365]  error=0.384
5th iteration weight=[0.69596241 0.3124593 ]  error=0.362
6th iteration weight=[0.61078798 0.42032938]  error=0.348
7th iteration weight=[0.6796005  0.33327726]  error=0.339
8th iteration weight=[0.62405298 0.40356557]  error=0.333
9th iteration weight=[0.66890088 0.34681937]  error=0.329
10th iteration weight=[0.63269312 0.39263373]  error=0.327
11th iteration weight=[0.66192557 0.35564546]  error=0.325
12th iteration weight=[0.63832471 0.38550802]  error=0.324
13th iteration weight=[0.65737891 0.36139843]  error=0.323
14th iteration weight=[0.64199546 0.38086335]  error=0.323
15th iteration weight=[0.65441531 0.36514831]  error=0.323
16th iteration weight=[0.64438813 0.37783587]  error=0.322
17th iteration weight=[0.65248359 0.36759255]  error=0.322
18th iteration w

In [67]:
from scipy.stats import entropy

entropy(np.array([0.5, 0.5, 0.5, 0.5]))

1.3862943611198906

In [74]:
p = np.array([0.5, 0.2, .2, 0.1])

In [75]:
-np.sum(p*np.log(p))

1.2206072645530173

In [76]:
entropy(p)

1.2206072645530175